# Generated by Django 3.1.3 on 2020-11-16 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000)),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('order_id', models.CharField(max_length=1000)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=1000)),
                ('currency', models.CharField(blank=True, max_length=100, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=64, null=True, unique=True, verbose_name='Email')),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobile Number')),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
